defaults:
  - default


callbacks:
  -
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${ckpt_dir}
    filename: "{step:06d}"
    save_weights_only: true
    every_n_train_steps: 10000
    verbose: true
  
  -
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: ${project_name}
  log_model: false
  reinit: true
