teacher:
  model_name_or_path: klue/bert-base

student:
  num_hidden_layers: 6

optim:
  # optimizer
  lr: 6e-4
  betas: 
    - 0.9
    - 0.999
  weight_decay: 0.01

  # scheduler
  scheduler: linear
  max_steps: ${trainer.max_steps}
  warmup_ratio: 0.05


ckpt_dir: ${ckpt_dir}
mlm: false
