teacher:
  model_name_or_path: klue/bert-base
  hidden_dropout_prob: 0
  attention_probs_dropout_prob: 0
  output_attentions: true
  output_hidden_states: true

student:
  model_name_or_path: /workspace/language-model-distillation/init
  num_hidden_layers: 6
  num_attention_heads: 12
  hidden_size: 384
  intermediate_size: 3072
  hidden_dropout_prob: 0
  attention_probs_dropout_prob: 0
  output_attentions: true
  output_hidden_states: true

optimizer:
  name: adamw
  lr: 6e-4
  betas: 
    - 0.9
    - 0.98
  weight_decay: 0.01

scheduler:
  name: linear
  max_steps: ${trainer.max_steps}
  warmup_ratio: 0.05


ckpt_dir: ${ckpt_dir}
mlm: false
