_target_: src.model.layer_relation.Model

defaults:
  - default

student:
  hidden_size: 384

num_relation_heads: 48
temperature: 0.3

teacher_embedding_index: 0
teacher_last_index: 11
student_embedding_index: 0
student_last_index: -1