defaults:
  - _self_
  - data: text
  - model: minilmv2
  - trainer: full

project_name: language-model-distillation
working_dir: ${hydra:runtime.cwd}
data_dir: ${working_dir}/data
ckpt_dir: ${working_dir}/ckpt
